---
- name: Git clone project
  git:
   repo: https://github.com/vitaliy-developer/vitaliy-katkalo.github.io.git
   clone: yes
   dest: /var/www/site

- name: Permission of the rights to the project
  file:
   path: /var/www/site/
   state: directory
   owner: www-data
   group: www-data
   recurse: yes
   mode: '755'
